export * from './general/alert.component';
export * from './home/dashboard.component';
export * from './idea-detail/idea-detail.component';
export * from './old/idea-edit.component';
export * from './ideas/idea-add.component';
export * from './idea-detail/modification column/idea-add-modification.component';
export * from './ideas/idea-search.component';
export * from './ideas/ideas.component';
export * from './idea-detail/argument coumn/arguments.component';
export * from './idea-detail/modification column/how-it-works.component';
export * from './idea-detail/modification column/modification-detail.component';
export * from './general/ideas-teaser.component';